#+TITLE: Yet untitled book on getting things done while crazy and forgiving yourself when you can't
#+AUTHOR: Clarissa Littler
#+OPTIONS: toc:nil

* Introduction
  Do you read productivity books and blogs, hoping to find a way to get more done each day, but feel ashamed because their advice doesn't work for you mental illness? Have you tried Writing Every Day and ended up hating yourself when you can't? If you have, then you and I have an awful lot in common. I spent my twenties with pretty severe, undiagnosed, mental illnesses, trying to figure out why I was having so much trouble functioning, concentrating, and why just holding down a full-time job left me so drained that I'd fall asleep by 6pm.

  I used to think I was just lazy, unfocused, and sometimes that I was just *stupid* and good-for-nothing. Since then, though, I ended up seeing a therapist---who ended up diagnosing me with cPTSD within a few minutes of talking with me---and have been learning to work /around/ the way my brain functions, rather than constantly fighting against myself. 

  It's not an easy task, nor one I would even say I'm particularly good at, so in a sense this book is just as much a set of reminders and tips for myself as it is for any particular audience. I still need reminders every day and I still often end up hating myself for the times I can't relate to the advice of all of productivity blogs and books I end up reading.

** My Background
   So as I'm writing this book, I'm in the middle of working on my doctorate in computer science, which has involved learning a lot of lessons on how to work mostly by myself on self-directed projects *while* managing stress, burnout, and mental illness. 

   I've had a lot of mixed success. So far I've had some bad breakdowns, been pretty self-sabotaging, had the closest time I ever came (and hopefully ever will) to succeeding in killing myself, and yet also have managed to not give up and keep trying. 
** No trick works for everyone (or: did you try exercising?)
   One of the first things I want to say in this text is that while I'm sharing a lot of my own thoughts about how *I* deal with my own mental illness and what *I* find useful, I want to be very clear that I don't think this applies to everyone else, not only because there are many different kinds of mental disability I don't have experience with, but also because there's so much variation between different people's experiences even *with* the same diagnoses I don't think there's any possible way for one person's experience to be universal.

   I decidedly do not want this book to be like the many self-help books and blogs that talk about the power of positive-thinking or yoga-ing or jogging your way out of being depressed and anxious. I'm not even deriding the people who *were* helped by positive thinking or exercise or any other trick they found useful. I simply believe that there is no silver bullet, no One Weird Trick, that will be a panacea.

   Instead, I just want to share some observations and tricks and thoughts, without any expectation that any of it will necessarily apply to anyone beyond myself. There is no one true way to be mentally ill. There is no one true way to be disabled. Please, don't blame yourself if some of the things in this text don't apply to your or aren't helpful. Your experiences are always legitimate and they are uniquely yours.

* When You've Never Had a Comfort Zone
  One piece of advice that I see *repeatedly* in productivity books and blogs is that you should try to get out of your "comfort zone". You can always find tips about how to get more done and turn your life around by being willing to "take risks" or "get out of your comfort zone". I've never really related to this advice because, well, I'm *literally never comfortable*. 
  
  I used to always feel like I was being incredibly grouchy or facetious when I made that joke, but the more I've thought about it and the more people I've talked to the more I think there's some truth to it: a lot of mental disabilities mean that you never get the opportunity to ever really be comfortable. 

  What I mean by this is that when you're constantly fighting anxiety or when you're hyper-vigilant or struggling to stay connected to reality, *everything* you do can carry a cognitive load that never lets you feel safe and in control.

  That's really what self-help books mean when they say "get out of your comfort zone", they're suggesting that you allow yourself to be unsafe and feel out of control, but in some kind of limited way. I understand the utility! It can be important to take risks, to try new things, to gamble on big ideas, but to me it always comes across as chiding, perhaps even insulting, during those times when getting out of bed in the morning felt like the limit of what I could do. 

  When you're dealing with fear that's outside of your control, fear that comes from mental illness and disability, then you may not have the ability to push any further: and that's okay! 

  It's alright to not have it in you to take further risks when you're already at your limits. You can allow yourself to have a little bit of safety when you need it.

  If you're like me, then this might be a very scary proposition. I'm always terrified that if I'm not ready to "get out of my comfort zone" every day, that I'm somehow just complacent and that I'll *never* actually take any risks or accomplish anything. It's always now or never. 

  Of course, that's not really how any of this works. It's not a dichotomy between pushing yourself into following your dreams *right this moment* or never, ever reaching them. 

  Allow yourself to consider *this day* in isolation. If you need *this day* in rest, you should take it. All those risks and ridiculous ideas you have can wait for you to have the strength to fight for them. 
* Exponential Growth of Sanity Points
  So I'm a total dork. I'm an oldschool console RPG player who played the *original* Final Fantasy for the NES when I was just a really little girl. MP (magic points) and HP (hit points), have thus been a metaphor that's as old to me as my own sentience. 

  I think that's why I picture my own mental health, only quarter jokingly, as sanity points (SP). On some level, it's not terribly different than the "spoon theory" (ref), but it's a metaphor that I find a bit more convenient.

  I find it helpful to visualize how many SP different actions throughout the day will cost me. I take stock of how many SP I seem to have each morning when I wake up. 
  (...)
* When Write Every Day Doesn't Work
  I always heard the maxim "write every day". Just write X words per day and you'll have an amazing career as a writer. It's what makes you a real writer. Real writers write whenever they can. Real writers can't be stopped from writing every day. Real writers claw their way, barehanded, from the depths of the underworld in order to reach their vintage typewriter and *write every day*.

  It's one of those things that people say, and I don't think it's bad advice *when you have the energy*. The problem I've found is that trying to "write every day"/"code every day"/..., is that when you're not giving yourself frequent days of rest you *will* burn out. 

  In my case, burnout tends to look like
  + inability to concentrate or remember what I was thinking
  + trouble remembering my own name
  + inability to recognize people I know
  + severe suicidal ideation
  + near-constant panic attacks

This is 

* Hitting Your Limits
* Needing Breaks
* Worth and Work
* Faking Sanity and why it shouldn't be necessary
* When You Can't (and Shouldn't) Fake It
* Recovering From a Breakdown
  If you're like me, then sometimes you're going to have a really, really bad breakdown. The kind that means you're not going to be functional for days or even weeks. I think it takes a lot of different forms. For some people, it's the inability to get out of bed for days at a time. For other's, it's overwhelming anxiety so strong it shuts out every other thought you have.

  For me, it tends to be really severe disassociation and missing time. I'll have gaps in my memories, even going as far as not being able to recall details of months prior to the breakdown. 

  I think it's really disheartening to try and get back into your work after having a period of being unable to do *anything*. It always makes me feel like my attempts to create things or work on my research are completely pointless, because I've lost *all* of my momentum and, if I haven't taken good enough notes (see the next chapter for more on that topic), I may have lost even the plan of what I was doing and all the insights I'd had.

  There will come a time, though, when you're finally ready to get back to your work. In my experience, it's a terrible idea to try and hit the ground running. If I try to push myself after a breakdown, I just end up feeling frustrated, depressed, and hopeless. What I think is much more productive is allotting yourself time to page information back in, expecting it to take longer than usual to get all the necessary bits and pieces back in your brain. Review your notes. Skim the books or papers you'd been reading before the breakdown. 

  Even if it doesn't feel like it, this paging in is serious work and takes a lot of time. Once you've done it, though, you'll have a much easier time picking up where you left off. 

  It's also completely okay to need to ramp back up to a full work day. I've had days where it's a good day if I can work for just half an hour before getting overwhelmed and exhausted. 
* Organizing Around Your Memory
  I've already talked a little bit about having "missing time", which is my largest issue of memory, but I know that problems with memory extend far beyond ptsd and dissociative disorders. So, when you have lots of problems with memory and retaining information, how do you work on projects that last more than a few days?

  The short answer is that you keep massive amounts of notes, on everything. The rest of this section, I want to talk about how *I* keep said notes and stay organized and what kinds of qualities I think a note taking system needs to have.

  The first of which, I think, is that it needs to be *easy to use*. When you're running low on SP, anything that has too much cognitive overhead is likely to be just not done. It's a lot like activation energy in chemistry. If you put in less energy, then *nothing* at all happens. 

  Next, I think, is that it needs to be a system that allows you to categorize your thoughts in an easy to find way. I think that's true of anyone, but when you have memory problems one of the truly difficult problems is when you've *done work you can't remember doing*. I know that I've had problems with this since my childhood, occasionally finding stories or notebooks full of rewritten rules to RPGs that I literally had no memory of ever writing, but it was clearly my handiwork. I still have the problem sometimes of "rediscovering" the same insight about a paper repeatedly, only finding evidence after the fact in some forgotten notebook that I'd already read it and had figured out the same thing. For this reason, any system for taking notes needs to be easily searchable. You don't want to unintentionally duplicate work.

  Also, your system of notetaking needs to be at least somewhat portable. You might need to write down thoughts as you're having them no matter where you are. I know that on some days I can lose whatever I was thinking mere moments later, so I need to write things down immediately. Again, I think this is partially just an experience everyone has some of the time, but I know that mental illness can seriously exacerbate the tendency. 

  My primary tool for note taking is [[http://orgmode.org/][org mode]], which is a major mode for Emacs (Emacs itself being a text-editor-turned-near-operating-system), along with Dropbox for synchronization and [[http://www.orgzly.com/][Orgzly]] for taking notes on my mobile. Entire books can be written about using org-mode for organizing your notes, and this isn't going to be one of them, so I would recommend starting with a resource such as [[http://doc.norang.ca/org-mode.html][Organize Your Life In Plain Text]] which is a *very* extensive tutorial in how to use the facilities in org-mode for keeping notes and organizing tasks and information.
  
* Communication and Anxiety
* Illness Isn't Procrastination
  If you're like me, you're constantly terrified that maybe you're just being lazy and have a terrible work ethic, and that there's nothing really wrong with you at all! Honestly, that's what I thought about myself for the vast majority of my life. It's only in recent years that I've started to understand the basic lesson that *illness* isn't the same as *procrastination*.

  Sometimes things you need to do seem too hard, too exhausting, just too *much*. I know that I have days when writing just doesn't work and times when I'm reading the same sentence of a paper over and over. At times like these, it's best to just put those tasks aside and let them be. 

  Please don't let anyone convince you that you're being lazy when you need to put something off that you just can't do. Far from being lazy, it's actually the difficult and responsible choice to allow yourself time to rest when you don't feel like you should. 

  Indeed, I think it's fairly unlikely that anyone who's mentally ill or disabled is actually going to be lazy. Why? Because when literally every day is hard, I don't think you can afford laziness. Laziness is more of a kind of entitlement, an expectation that one should be able to get things without putting in the same amount of work that everyone else has to. I think of all the many many people I have known who have been mentally ill, there has been perhaps only a single person among them who was actually lazy and even that case is debatable.

  That's why I'm confident in saying that if you're reading this book, it's very unlikely you're an entitled person who wants things handed to them. Try to remind yourself of that if you feel like you're just procrastinating. Not being able to handle doing something now isn't the same as putting it off because you don't care and resent the work.
* Invisible Disability Is Still Disability
* Mind Over Matter When Mind Is The Matter
* Permission to Fail, Permission to Try
  I think one of the hardest things I deal with in both my personal projects and in my career is not feeling like I have "permission to fail". I'm hardly the first person to talk about the concept, about the need in creative work to know that it's alright to take chances and make mistakes, but I want to specifically discuss my experiences of dealing with it as someone who is severely mentally ill. I would call my experiences something more akin to "permission to be imperfect"

  My problem isn't just that I'm afraid of messing something up dramatically or doing a terrible job. It's more that I'm petrified of even making the slightest mistake. Even while writing this book I have been constantly fighting the urge to delete this repository and nuke it all from orbit. Before each push, I have to fight back a hyperventillating panic because I'm expecting that somehow, someway, someone is going to read the in-progress draft and get so angry at something I said that I'll find hundreds of messages in my inbox telling me to kill myself because I'm clearly so worthless and arrogant for thinking that I was allowed to write any of this. 

  It's an irrational response. I know it's an irrational response. It's also a pattern of disordered thinking that's deep seated into how my brain functions. As we've already seen, just knowing that you're experiencing disordered thinking doesn't take the thinking away any more than knowing you have the flu provides you with an immediate cure.

  What happens, though, when you do make a mistake? We all make mistakes. That's a given. What I personally have trouble with is the panic attack that comes *with* the mistake. Like a lot of my panic attacks, it will probably sound silly to say that whenever I actually mess something up that I get afraid for my very safety. 
* Needing Validation Isn't Manipulative
  Everyone needs validation sometimes. I think it's universal, because we are social creatures. I think the only people I've seen who claim that they *don't* care about getting some praise or acknowledgment have been folks who are so used to it they can't imagine what not feeling validated is like.

  If your mental illness doesn't allow you to have a proper perspective on yourself, though, you're going to need a lot more validation than average. This is okay, healthy even! It's alright to try and rely on other people you trust to help correct your pathological beliefs. 

  It's not inherently manipulative or petty or vain to need someone to tell you that you're doing a good job. It only crosses that bad line if there's *consequences* when someone can't meet that need, if you punish them for not guessing what you wanted to hear, but that's not unusual to being mentally ill: that's just always the bad way to get validation. 

  At this point, I tend to crowd source my need for validation. I'll send out a tweet spelling out what I managed to get done and explicitly ask for someone to tell me whether that was good enough for a work down. I like doing it that way because it feels very low stress. If someone reads that tweet and wants to say something, they can. If they don't agree or don't want to bother trying to reassure me, that's okay to, they don't have to do it and I won't resent them for it.
* Learning to take a compliment
* Bootstrapping Confidence
* Excuses are okay
* Working With Others
* Diagnosis Isn't Magic
* When Sprinting is Dangerous
* When Creativity Makes You Crazy
* Mistakes Aren't Lethal
* Preventing Spirals
* Dealing With Being Overwhelmed
* Self-Sabotage
* Hating Yourself and Distorted Mirrors
* Needing Help Is Okay
* On Incremental Progress and a Cheesy Metaphor
* Choosing reasonable goals
* Ups and Downs
* Hypervigilance and Focus
* Riding Out Bad Brain States
* The Worst Moments Aren't Eternal
* Envying the Healthy

